name: On Code Change

on: [push]

env:
  PRIMARY_RELEASE_BRANCH: master

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to GitHub registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8
      - name: Define image tag
        shell: bash
        run: |
          if [[ "${{ steps.branch-name.outputs.current_branch }}" != "${{ env.PRIMARY_RELEASE_BRANCH }}" ]]; then
            echo "JAHIA_TAG=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV
          else
            echo "JAHIA_TAG=latest" >> $GITHUB_ENV
          fi
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/jahia/qa-mf-unomi-tracker-site:${{ env.JAHIA_TAG }}
          platforms: linux/amd64,linux/arm64
