name: On Code Change

on: [push]

env:
  PRIMARY_RELEASE_BRANCH: master

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2
      - name: Define image tag
        shell: bash
        run: |
          if [[ "${{ steps.branch-name.outputs.current_branch }}" != "${{ env.PRIMARY_RELEASE_BRANCH }}" ]]; then
            echo "JAHIA_TAG=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV
          else
            echo "JAHIA_TAG=latest" >> $GITHUB_ENV
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: jahia/qa-mf-unomi-tracker-site:${{ env.JAHIA_TAG }}